name: bootjack_datepicker_example_app
description: A web app example for bootjack_datepicker.

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  bootjack_datepicker:
    path: ../

dev_dependencies:
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_web_compilers: ^3.0.0
